version: "3"
services:

### Nginx Server ###

  nginx:
    build:
      context: ./nginx
    volumes:
      - ${HOST_APPLICATIONS_PATH}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_HOST_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php7-fpm
    networks:
      - backend

### PHP7-FPM ###

  php7-fpm:
    build:
      context: ./php-fpm/7.1
    volumes:
      - ${HOST_APPLICATIONS_PATH}:/var/www
      - ./php-fpm/7.1/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - backend

### MySQL ###

  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${HOST_DATA_SAVE_PATH}/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    networks:
      - backend

### Redis ###

  redis:
    build: ./redis
    volumes:
      - ${HOST_DATA_SAVE_PATH}/redis:/data
    ports:
      - "${REDIS_HOST_PORT}:6379"
    networks:
      - backend


### Networks Config ############################################

networks:
  backend:
    driver: bridge

### Volumes Config #############################################

volumes:
  mysql:
  redis:
